aws-access-key               = ""
aws-secret-key               = ""
aws-region                   = ""
listings-service-db-password = ""
listings-service-db-username = ""
users-service-db-password    = ""
users-service-db-username    = ""
